# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yJv4f61h-j6LiQIveI2vdqZeEudSJfVt
"""

import json
import getpass

students_file_path = './students_json'

# print(students_json_data['students'])


def read_students_json():
    with open(students_file_path, "r") as json_file:
        students_json_data = json.load(json_file)

    return students_json_data


def write_students_json(students_json_data):
    with open(students_file_path, 'w') as outfile:
        json.dump(students_json_data, outfile, ensure_ascii=False, indent=4)
{
    "students": [
      {
          'name': 'kim', 
          'age': '11', 
          'job': 'element_student', 
          'id': 'kimbab', 
          'password': '741'
        },
      {
        'name': 'lee', 
        'age': '23', 
        'job': 'univ_student', 
        'id': 'tteok', 
        'password': '852'
    },
      {
        'name': 'park', 
        'age': '19', 
        'job': 'designer', 
        'id': 'cake', 
        'password': '963'
    }
      
    ]
  }

def name(name):
  print ['name']

def age(age):
  print ['age']

def job(job):
  print ['job']

def id(id):
  print ['id']

def password(password):
  print ['password']


name(['name'])

# - 학생 이름 전부 출력해보기
def other_users():
  for i in range(len(students)):
    print(studnets[i]['name'])

# - 20살 미만 학생 open의 쓰기모드를 활용하여 넣어보기
g=open('student.json','w')
for i in range(len(studnets)):
  if students[i]['age'] <20:
    studnets.append('age')
f.close

# - 성인이 아닌 학생 출력하기 (20세 미만..)
for i in range(len(studnets)):
  if students[i]['age'] <20:
    print(i)

# - 조건문으로 아이디를 안넣으면 쓰기 안되게 막아보기
if id == False:
  print(None)